name: 'Backend testing'

on: push
permissions:
  id-token: write
  contents: read
jobs:
  python-unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo
      - name: Run test
        run: python -m unittest tests.count_test
  
  terraform-deployment:
      needs: python-unit-test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-region: us-east-1
            role-to-assume: arn:aws:iam::779765511615:role/github-action
        - name: Terraform setup
          uses: hashicorp/setup-terraform@v2
        - name: Terraform Init
          run: terraform init
        - name: Terraform Plan
          run: terraform plan -input=false
        - name: Terraform Apply
          run: terraform apply -auto-approve

    
   

